services:
  - type: web
    name: spotter-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && gunicorn trucking_eld.wsgi:application --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: spotter-db
          property: connectionString
