# Generated by Django 4.2.7 on 2025-07-21 09:16

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('rest', 'Rest Stop'), ('fuel', 'Fuel Stop'), ('waypoint', 'Waypoint')], max_length=50)),
                ('distance_from_previous', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('duration_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='eld_api.trip')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='LogSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('driver_name', models.CharField(max_length=255)),
                ('vehicle_id', models.CharField(default='Truck-001', max_length=50)),
                ('driving_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('on_duty_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('off_duty_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('sleeper_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('cycle_hours_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('cycle_hours_remaining', models.DecimalField(decimal_places=2, default=Decimal('70.00'), max_digits=5)),
                ('total_distance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('fuel_stops', models.IntegerField(default=0)),
                ('rest_stops', models.IntegerField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sheets', to='eld_api.trip')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('driving', 'Driving'), ('on_duty', 'On Duty'), ('off_duty', 'Off Duty'), ('sleeper', 'Sleeper Berth')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('log_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='eld_api.logsheet')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
