# Generated by Django 4.2.7 on 2025-07-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='current_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
